'use strict';
// Index freshness against the tree that git is about to keep.
//
// index.db is gitignored, so CI cannot ask "is last_index older than HEAD"
// by reading the store. The committed contract is .vnodes/manifest.json:
// per-file content hashes written at the end of every index run. If someone
// commits code without reindexing, those hashes disagree with the tree, and
// `vnodes check` fails. The pre-commit hook reindexes and stages the
// manifest so a kept change cannot land without an up-to-date index.
const fs = require('node:fs');
const os = require('node:os');
const path = require('node:path');
const { loadConfig } = require('./config');
const { gitDir, headSha, gitRun } = require('./git');

const BEGIN = '# vnodes:begin';
const END = '# vnodes:end';

function checkIndex(projectRoot) {
  const cfg = loadConfig(projectRoot);
  const { expectedManifest } = require('./indexer');
  const manPath = path.join(projectRoot, '.vnodes', 'manifest.json');
  if (!fs.existsSync(manPath)) {
    return {
      ok: false,
      state: 'no_manifest',
      reason: `${projectRoot} has no .vnodes/manifest.json — run: vnodes index`,
      head: headSha(projectRoot),
      last_index_git_head: null,
      last_index: null,
      mismatches: [],
      mismatch_count: 0,
      fix: 'vnodes index && git add .vnodes/manifest.json',
    };
  }
  let recorded = {};
  try {
    recorded = JSON.parse(fs.readFileSync(manPath, 'utf8')).files || {};
  } catch (e) {
    return {
      ok: false,
      state: 'unreadable_manifest',
      reason: `manifest.json could not be parsed: ${e.message}`,
      head: headSha(projectRoot),
      last_index_git_head: null,
      last_index: null,
      mismatches: [],
      mismatch_count: 0,
      fix: 'vnodes index && git add .vnodes/manifest.json',
    };
  }

  const expected = expectedManifest(projectRoot, cfg);
  const mismatches = [];
  for (const [file, hash] of Object.entries(expected)) {
    if (!(file in recorded)) mismatches.push({ path: file, kind: 'not_in_index' });
    else if (recorded[file] !== hash) mismatches.push({ path: file, kind: 'hash_mismatch' });
  }
  for (const file of Object.keys(recorded)) {
    if (!(file in expected)) mismatches.push({ path: file, kind: 'removed' });
  }

  let lastIndex = 0;
  let lastHead = null;
  try {
    const { openStoreReadOnly } = require('./store');
    const db = openStoreReadOnly(path.join(projectRoot, '.vnodes'));
    if (db) {
      lastIndex = Number(db.prepare("SELECT value FROM meta WHERE key = 'last_index'").get()?.value || 0);
      lastHead = db.prepare("SELECT value FROM meta WHERE key = 'last_index_git_head'").get()?.value || null;
      db.close();
    }
  } catch {}
  if (lastHead === '') lastHead = null;

  const head = headSha(projectRoot);
  const ok = mismatches.length === 0;
  let reason;
  if (!ok) {
    reason = `index does not match the current tree (${mismatches.length} file(s)) — run: vnodes index`;
  } else if (head && lastHead && head !== lastHead) {
    reason = 'manifest matches the current tree; git HEAD moved since last index (expected after a commit)';
  } else {
    reason = 'manifest matches the current tree';
  }
  return {
    ok,
    state: ok ? 'current' : 'stale',
    reason,
    head,
    last_index_git_head: lastHead,
    last_index: lastIndex || null,
    mismatches: mismatches.slice(0, 20),
    mismatch_count: mismatches.length,
    fix: 'vnodes index && git add .vnodes/manifest.json',
  };
}

function hookBlock(bin) {
  return `${BEGIN}
# generated by vnodes hook install — reindex and stage .vnodes/manifest.json
node ${JSON.stringify(bin)} hook pre-commit || exit 1
${END}
`;
}

function installHook(projectRoot) {
  const dir = gitDir(projectRoot);
  if (!dir) return { ok: false, error: 'not a git repository — init one, or run vnodes check in CI without a hook' };
  const hookPath = path.join(dir, 'hooks', 'pre-commit');
  const bin = path.join(__dirname, '..', 'bin', 'vnodes.js');
  const block = hookBlock(bin);
  let existing = '';
  try { existing = fs.readFileSync(hookPath, 'utf8'); } catch {}
  let next;
  const start = existing.indexOf(BEGIN);
  const end = existing.indexOf(END);
  if (start >= 0 && end > start) {
    next = existing.slice(0, start) + block.trimEnd() + existing.slice(end + END.length).replace(/^\n/, '');
  } else if (!existing.trim()) {
    next = `#!/bin/sh\n${block}`;
  } else {
    next = existing.replace(/\n?$/, '\n\n') + block;
  }
  if (!next.startsWith('#!')) next = `#!/bin/sh\n${next}`;
  fs.mkdirSync(path.dirname(hookPath), { recursive: true });
  fs.writeFileSync(hookPath, next);
  fs.chmodSync(hookPath, 0o755);
  return { ok: true, hook: hookPath, bin };
}

function runPreCommit(projectRoot) {
  if (path.resolve(projectRoot) === path.resolve(os.homedir())) {
    return { ok: false, error: 'refusing to index the home directory from a hook' };
  }
  const { runIndex } = require('./indexer');
  const r = runIndex(projectRoot, loadConfig(projectRoot));
  const check = checkIndex(projectRoot);
  if (!check.ok) return { ok: false, files: r.files, edges: r.edges, ms: r.ms, check };
  let staged = false;
  if (gitDir(projectRoot)) {
    const add = gitRun(projectRoot, ['add', '.vnodes/manifest.json']);
    staged = add.ok;
    if (!add.ok) return { ok: false, error: add.stderr || 'git add .vnodes/manifest.json failed', check };
  }
  return { ok: true, files: r.files, nodes: r.nodes, edges: r.edges, ms: r.ms, staged, check };
}

module.exports = { checkIndex, installHook, runPreCommit };
